### ISSUE TITLE
Sporadic NoSuchFileError in processFinishedJob

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-lib#24]
```
Traceback (most recent call last):
  File "/home/mesosbox/venv/bin/toil-rnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/mesosbox/venv/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 505, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 571, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 794, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 692, in mainLoop
    innerLoop(jobStore, config, batchSystem, toilState, jobBatcher, serviceManager, statsAndLogging)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 935, in innerLoop
    jobBatcher.processFinishedJob(jobBatchSystemID, result, wallTime=wallTime)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 294, in processFinishedJob
    with jobWrapper.getLogFileHandle( self.jobStore ) as logFileStream:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 546, in readFileStream
    info = self.FileInfo.loadOrFail(jobStoreFileID)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 864, in loadOrFail
    raise NoSuchFileException(jobStoreFileID, customName=customName)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'c2c91768-430b-4c96-b7ed-054753defe07' does not exist
```

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/toil#1153
